# Generated by Django 4.2.3 on 2023-11-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUsers',
        ),
    ]
