# Generated by Django 4.2.3 on 2023-11-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSM', '0002_delete_appusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('adress', models.TextField(blank=True, max_length=60, null=True)),
                ('position', models.CharField(choices=[('Director', 'Director'), ('State engineer in statistics', 'State engineer in statistics'), ('State engineer in informatic', 'State engineer in informatic'), ('Senior technician in informatics', 'Senior technician in informatics')], max_length=40, null=True)),
                ('ar_position', models.CharField(choices=[('مدير المؤسسة', 'مدير المؤسسة'), ('مهندس دولة في الإحصاء', 'مهندس دولة في الإحصاء'), ('مهندس دولة في الإعلام الألي', 'مهندس دولة في الإعلام الألي'), ('تقني سامي في الإعلام الألي', 'تقني سامي في الإعلام الألي')], max_length=40, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
