# Generated by Django 4.2.3 on 2023-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0004_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Statistical Engineering', 'Statistical Engineering'), ('Informatic Engineering', 'Informatic Engineering'), ('Informatic Technical Senior', 'Informatic Technical Senior')], max_length=40, null=True),
        ),
    ]
