# Generated by Django 4.2.3 on 2023-11-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0005_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
