# Generated by Django 4.2.7 on 2023-12-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0015_alter_employee_position'),
        ('CSM', '0015_messages_parent_message_messages_reciever_del_and_more'),
    ]

    operations = [
    ]
