# Generated by Django 4.2.7 on 2023-12-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0017_alter_employee_position_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='child_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='CSM.messages'),
        ),
    ]
