# Generated by Django 4.2.7 on 2023-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0018_messages_child_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='childs_not_read',
            field=models.BooleanField(default=True),
        ),
    ]
