# Generated by Django 4.2.7 on 2023-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0020_rename_childs_not_read_messages_childs_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='childs_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
