# Generated by Django 4.2.7 on 2023-12-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSM', '0019_remove_messages_child_message'),
        ('CSM', '0022_remove_messages_childs_is_read'),
    ]

    operations = [
    ]
